name: Generate a build and push to another branch

on:
    push:
        branches:
            - main # The branch name your are commit the new changes

jobs:
    build-themes:
        runs-on: ubuntu-latest
        name: Build and Push Themes
        steps:
            - name: git-checkout
              uses: actions/checkout@v3

            - name: Install dependencies for both themes
              run: |
                cd capitola && npm install
                cd ../scuba-tutor && npm install

            - name: Build capitola theme
              run: cd capitola && npm run build

            - name: Push capitola build to build-parent branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: build-parent
                  FOLDER: capitola/build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MESSAGE: 'Build: ({sha}) {msg}'

            - name: Build scuba-tutor theme
              run: cd scuba-tutor && npm run build

            - name: Push scuba-tutor build to build-child branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: build-child
                  FOLDER: scuba-tutor/build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MESSAGE: 'Build: ({sha}) {msg}'
